worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # 配置负载均衡池，包含两个后端实例
    upstream backend_api {
        # 默认使用轮询算法。
        # 加权轮询：server mall-api-1:8081 weight=2;
        # IP 哈希: 将来自同一客户端的请求始终分发到同一台服务器，适用于需要会话保持的场景。
        # ip_hash;
        
        server mall-api-1:8081;
        server mall-api-2:8082;
    }

    server {
        listen       80;
        server_name  localhost;

        # 动静分离：处理静态资源请求
        # 所有不符合特定前缀的请求，默认去 html 文件夹下找静态文件
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # 动静分离：处理动态 API 请求
        # 约定前端所有发给后端的请求都以 /api/ 开头
        location /api/ {
            # 转发到上面定义的负载均衡池
            proxy_pass http://backend_api/;
            
            # 保留真实的客户端信息
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}